version: '3.8'

services:
  db:
    image: postgres:14
    container_name: audio_temka_db
    environment:
      POSTGRES_USER: gemini
      POSTGRES_PASSWORD: gemini
      POSTGRES_DB: gemini
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
