# Generated by Django 6.0.3 on 2026-03-26 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_user_email_optional'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('mime_type', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_generations', to='users.user')),
            ],
            options={
                'db_table': 'main_audiogeneration',
                'ordering': ['-created_at'],
            },
        ),
    ]
